### ISSUE TITLE
Concrete API implementations differ from one another

### ISSUE THREAD

**Issue by HQarroum** [Yoctol/messaging-apis#184]
Each implementations of a messaging API (e.g `messaging-api-messenger` and `messaging-api-line`) differ in their API which prevents polymorphic use-cases where I pass an instance of a messaging API to a component of my application without explicitely *knowing* what real API this is.

For instance,  `messaging-api-messenger`  implements the `sendText` method where  `messaging-api-line`  implements the `pushText` method for sending messages, where they could both implement the same method name.

Is there any reason behind this choice ?

**Comment by chentsulin** [comment]
It's intentional. We try to keep all of method names here to correspond with the original platform docs or API keys and do not have any hidden black magic. Because of that, we can search keywords from official docs directly.

For examples: (LINE APIs is so different from Messenger)
replyText - https://developers.line.me/en/docs/messaging-api/reference/#send-reply-message
pushText - https://developers.line.me/en/docs/messaging-api/reference/#send-push-message
multicastText - https://developers.line.me/en/docs/messaging-api/reference/#send-multicast-message

If you are looking for a framework to build your cross-platform bots, maybe you will like Bottender https://github.com/Yoctol/bottender.

**Comment by HQarroum** [comment]
Ok thanks for the response and the pointer!
