### ISSUE TITLE
[Type] how can i get type to use ?

### ISSUE THREAD

**Issue by ninxxxxx** [Yoctol/messaging-apis#570]
I have looked into the code in the repo, there were written by typescript (that's cool for me) but after install, I can't find type to use. what am I missing? there are anyway to use it? please let me know

**Comment by chentsulin** [comment]
Hi @ninxxxxx, that's because those types was added in 1.0.0-beta releases. You can install them by using the `@next` tag:

```sh
npm install messaging-api-xxx@next
```

You might found that the main goal of this repo recently is to support delivering features in [Bottender](https://github.com/Yoctol/bottender). So, if you want to find the v1 document of those client, you may refer to Bottender API docs, for example, [MessengerClient](https://bottender.js.org/docs/en/api-messenger-client).

Anyway, we will release 1.0 version of messaging-apis very soon (maybe next month).

**Comment by ninxxxxx** [comment]
wow that's great. hope it's done soon, can't wait :D

**Comment by chentsulin** [comment]
Sorry for being so late. Now you can import these types in v1 official release:

```ts
import { MessengerTypes } from 'messaging-api-messenger';
import { LineTypes } from 'messaging-api-line';
import { SlackTypes } from 'messaging-api-slack';
import { TelegramTypes } from 'messaging-api-telegram';
import { ViberTypes } from 'messaging-api-viber';
import { WechatTypes } from 'messaging-api-wechat';
```
